### ISSUE TITLE
Error message about "SCCS/s.makefile" - no rule to make target

### ISSUE THREAD

**Issue by arjenmarkus** [tcllab/tclmake#1]
I decided to try out tclmake and started with just about the simplest makefile I could think of:
`
all:	hello.exe

hello.exe:	hello.f90
	gfortran -o hello hello.f90
`
I did not install tclmake, but ran it directly via "tclsh ..\bin\tclmake" (on Windows). The output, however, was:
`
Tclmake, version 2.0...
D:/tcl-programs/tclmake/testje
No rule to make target 'SCCS/s.makefile', needed by 'makefile'.  Stop.
`
What should I do?

**Comment by arjenmarkus** [comment]
From the source code and the documentation I see that I need to arrange my makefile in a different way - will have to study the documentation in some detail ;)

**Comment by tcllab** [comment]
Tclmake failed to find your makefile, and so fell back to the default makefile in the mk subdirectory.  The rules for finding a makefie are in doc/parsing.html.

You can specify a makefile explicitly using the -f command-line option.

**Comment by tcllab** [comment]
Also, the recipe for updating your target must be valid Tcl, and the recipe code must be indented just as in GNU make.  So your makefile should appear something like:

```
all: hello.exe

hello.exe: hello.f90
    exec gfortran -o hello hello.f90
```

**Comment by tcllab** [comment]
Added a warning message to the default makefile so the user is aware of what is happening if no other makefile is successfully selected.

**Comment by arjenmarkus** [comment]
Thanks for clarifying this :).
