### ISSUE TITLE
Error "no rule to make target"whereas the file in question is present

### ISSUE THREAD

**Issue by arjenmarkus** [tcllab/tclmake#2]
As a follow-up on ticket #1 I reran tclmake with the -f option. The result:
`
Tclmake, version 2.0...
D:/tcl-programs/tclmake/testje
No rule to make target './hello.f90', needed by 'hello.exe'.  Stop.
`
The file "./hello.f90" is present in the directory where I run tclmake (I started with "hello,f90", then tried to explicit).

It does work if I use the absolute path for the file.

**Comment by tcllab** [comment]
Sorry for the inconvenience, I believe this is related to an issue found and fixed yesterday.  It should work if you use the latest commit.

Thanks for continuing to try.

**Comment by arjenmarkus** [comment]
Yes, this solves it. See my comments to issue #3 too.
